version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  heroku: circleci/heroku@x.y # Use the Heroku orb in your config

workflows:
    heroku_deploy:
    jobs:
        - build
        - heroku/deploy-via-git:
            requires:
            - build # only run deploy-via-git job if the build job has completed
            filters:
            branches:
                only: main

jobs:
  build:
    working_directory: ~/bte-nutrition-calc
    docker:
      - image: circleci/ruby:2.7.4
        environment:
          PGHOST: localhost
          PGUSER: Nutrition_Calculator
          RAILS_ENV: test
      - image: postgres:14.4
        environment:
          POSTGRES_USER: Nutrition_Calculator
          POSTGRES_DB: Nutrition_Calculator_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: Nutrition_Calculator
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:migrate
      - run: bundle exec rspec