version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  # heroku: circleci/heroku@1.0.1

jobs:
  build:
    working_directory: ~/bte-nutrition-calc
    docker:
      - image: circleci/ruby:2.7.4
        environment:
          PGHOST: localhost
          PGUSER: Nutrition_Calculator
          RAILS_ENV: test
      - image: postgres:14.4
        environment:
          POSTGRES_USER: Nutrition_Calculator
          POSTGRES_DB: Nutrition_Calculator_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run:
          name: Nutrition_Calculator
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:migrate
      - run: bundle exec rspec

      - checkout
        - run:
            name: Deploy Main to Heroku
            command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main


# workflows:
#     heroku_deploy:
#     jobs:
#       - build
#       - heroku/deploy-via-git:
#           requires:
#             - build 
#           filters:
#             branches:
#               only: main