version: 2.1
# orbs:
#   ruby: circleci/ruby@0.1.2 
  # heroku: circleci/heroku@1.0.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: Nutrition_Calculator
      PGPASSWORD: ""
      RAILS_ENV: test

      steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      # - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build


# jobs:
#   build:
#     working_directory: ~/bte-nutrition-calc
#     docker:
#       - image: circleci/ruby:2.7.4
#         environment:
#           PGHOST: localhost
#           PGUSER: Nutrition_Calculator
#           RAILS_ENV: test
#       - image: postgres:14.4
#         environment:
#           POSTGRES_USER: Nutrition_Calculator
#           POSTGRES_DB: Nutrition_Calculator_test
#           POSTGRES_PASSWORD:
#     steps:
#       - checkout
#       - run:
#           name: Nutrition_Calculator
#           command: bundle -v
#       - ruby/bundle-install

#       - checkout
#       - run: bundle install --path vendor/bundle
#       - run: bundle exec rails db:migrate
#       - run: bundle exec rspec


# workflows:
#     heroku_deploy:
#     jobs:
#       - build
#       - heroku/deploy-via-git:
#           requires:
#             - build 
#           filters:
#             branches:
#               only: main